---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: pip
    run_list: recipe[apt::default]
    run_list: recipe[docker_registry::install]
    attributes:
      docker_registry:
        install_type: pip

  - name: docker
    run_list: recipe[apt::default]
    run_list: recipe[docker_registry::install]
    attributes:
      docker_registry:
        install_type: docker
