---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: docker
    run_list: recipe[docker_registry::default]
#    attributes:
#     docker_registry:
