# Rubocop,  we're buddies and all,  but we're going to have to disagree on the following -

SingleSpaceBeforeFirstArg:
  Enabled: false

UnusedBlockArgument:
  Enabled: false

WordArray:
  MinSize: 5

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 42

Style/RegexpLiteral:
  Enabled: false
